# mybatis-plus配置
mybatis-plus:
  # 扫描Mapper接口对应的XML文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 日志
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 命名自动驼峰转换
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 主键类型，auto：数据库id自增
      id-type: auto