spring:
  profiles:
    active: dev
  application:
    # 声明应用名称
    name: order-service

# 日志配置
logging:
  # 指定日志配置文件位置
  config: log4j2.xml

# eureka配置
eureka:
  client:
    # 是否将自己注册到eureka中
    register-with-eureka: false
    # 是否从eureka中获取信息
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka