spring:
  profiles:
    active: eureka

# 日志配置
logging:
  # 指定日志配置文件位置
  config: log4j2.xml

http:
  pool:
    # 连接超时
    connectTimeout: 5000
    connectionRequestTimeout: 5000
    defaultMaxPerRoute: 20
    # 最大连接数
    maxTotal: 100
    # 服务器返回数据(response)的时间
    socketTimeout: 500000
    validateAfterInactivity: 30000

mybatis-plus:
  # 扫描Mapper接口对应的XML文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 日志
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 命名自动驼峰转换
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 主键类型，auto：数据库id自增
      id-type: auto