spring:
  application:
    # 声明应用名称
    name: order-service
  profiles:
    active: nacos

# 日志配置
logging:
  # 指定日志配置文件位置
  config: log4j2.xml

mybatis-plus:
  # 扫描Mapper接口对应的XML文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 日志
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 命名自动驼峰转换
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 主键类型，auto：数据库id自增
      id-type: auto