server:
  port: 9000

spring:
  application:
    # 声明应用名称
    name: eureka-server

# 日志配置
logging:
  # 指定日志配置文件位置
  config: log4j2.xml

# eureka配置
eureka:
  client:
    # 指定 Eureka 服务端的地址
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka
    # 是否在启动时向 Eureka 注册中心注册服务实例
    register-with-eureka: false
    # 是否在启动时从 Eureka 注册中心获取已注册的服务实例信息
    fetch-registry: false
    # 向服务端发送一次心跳的间隔时间, 默认30
    instance-info-replication-interval-seconds: 30
    # 服务实例租约到期的时间
    # 规定的时间内未收到心跳，Eureka 服务端会认为租约过期，服务实例将被标记为不健康并可能被剔除。
    initial-instance-info-replication-interval-seconds: 40
  # 服务实例的主机名, 用于在 Eureka 注册中心标识该实例
  instance:
    # 解决报错
    # 由 spring.profiles 引起
    # ERROR ReplicationTaskProcessor(:) - Network level connection to peer localhost; retrying after delay
#    hostname: localhost
  server:
    # 保护机制, 默认开启。关闭后, 保注册中心将不可用的实例剔除
    enable-self-preservation: true
  # 是否启用健康检查, 默认为 true
  health-check-enabled: true
  # 定义健康检查的 URL 路径, 默认为 /actuator/health
  health-check-url-path: /actuator/health
